FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

FROM alpine:latest
COPY --from=builder /app/server /server
RUN apk add --no-cache sqlite
EXPOSE 8080
CMD ["/server"]
