FROM golang:bookworm AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o server ./cmd/server

FROM debian:bookworm-slim
COPY --from=builder /src/server /server
EXPOSE 5562
CMD ["/server"]
