// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddFeed(arg1:string):Promise<models.Feed>;

export function AddFilterRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateNote(arg1:number,arg2:string):Promise<models.Note>;

export function DeleteFeed(arg1:number):Promise<void>;

export function DeleteFilterRule(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function FilterAllArticles():Promise<void>;

export function FilterArticle(arg1:number):Promise<boolean>;

export function GenerateSummary(arg1:number):Promise<string>;

export function GetAIConfig():Promise<models.AIProviderConfig>;

export function GetAppState():Promise<models.AppState>;

export function GetArticle(arg1:number):Promise<models.Article>;

export function GetArticles(arg1:number,arg2:string):Promise<Array<models.Article>>;

export function GetFeeds():Promise<Array<models.Feed>>;

export function GetFilterRules():Promise<Array<models.FilterRule>>;

export function GetNotes():Promise<Array<models.Note>>;

export function OpenExternal(arg1:string):Promise<void>;

export function ReadNote(arg1:number):Promise<string>;

export function RefreshAllFeeds():Promise<void>;

export function RefreshFeed(arg1:number):Promise<void>;

export function SaveAIConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;
