// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFeed(arg1) {
  return window['go']['main']['App']['AddFeed'](arg1);
}

export function AddFilterRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFilterRule'](arg1, arg2, arg3);
}

export function CreateNote(arg1, arg2) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2);
}

export function DeleteFeed(arg1) {
  return window['go']['main']['App']['DeleteFeed'](arg1);
}

export function DeleteFilterRule(arg1) {
  return window['go']['main']['App']['DeleteFilterRule'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function FilterAllArticles() {
  return window['go']['main']['App']['FilterAllArticles']();
}

export function FilterArticle(arg1) {
  return window['go']['main']['App']['FilterArticle'](arg1);
}

export function GenerateSummary(arg1) {
  return window['go']['main']['App']['GenerateSummary'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetArticle(arg1) {
  return window['go']['main']['App']['GetArticle'](arg1);
}

export function GetArticles(arg1, arg2) {
  return window['go']['main']['App']['GetArticles'](arg1, arg2);
}

export function GetFeeds() {
  return window['go']['main']['App']['GetFeeds']();
}

export function GetFilterRules() {
  return window['go']['main']['App']['GetFilterRules']();
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function ReadNote(arg1) {
  return window['go']['main']['App']['ReadNote'](arg1);
}

export function RefreshAllFeeds() {
  return window['go']['main']['App']['RefreshAllFeeds']();
}

export function RefreshFeed(arg1) {
  return window['go']['main']['App']['RefreshFeed'](arg1);
}

export function SaveAIConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveAIConfig'](arg1, arg2, arg3, arg4, arg5);
}
